- name: Disable IPv6 on all interfaces
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    state: present

- name: Disable IPv6 
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    state: present
