---
- name: Remove files and folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/dhcp
    - /var/lib/dhcpcd5
    - /var/run
    - /var/spool
    - /var/lock
    - /etc/resolv.conf
    - /var/lib/systemd/random-seed

- name: Create sysmlinks
  file:
    src: /tmp
    dest: "{{ item }}"
    state: link
  with_items:
    - /var/lib/dhcp 
    - /var/lib/dhcpcd5
    - /var/run
    - /var/spool
    - /var/lock

- name: Touch resolv.conf
  file:
    path: "{{ item }}"
    state: touch
  with_items:
    - /tmp/dhcpcd.resolv.conf
    - /tmp/random-seed

- name: Create sysmlink for resolv.conf
  file:
    src: /tmp/dhcpcd.resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: Create sysmlink random-seed
  file:
    src: /tmp/random-seed
    dest: /var/lib/systemd/random-seed
    state: link

- name: Copy systemd-random-seed.service
  copy:
    src: lib/systemd/system/systemd-random-seed.service
    dest: /lib/systemd/system/systemd-random-seed.service
    owner: root
    group: root

- name: Systemd daemon relaod
  systemd:
    daemon_reload: yes
