---
- name: Purge previous packages
  include_tasks: purge-packages.yml

- name: Disable services
  include_tasks: disable-services.yml

- name: Change rsyslog for busybox-syslog
  include_tasks: syslog.yml

- name: Disable swap
  include_tasks: disable-swap.yml

- name: Delete folders and link them
  include_tasks: delete-link-folders.yml

- name: Update /etc/fstab configuration to RO
  include_tasks: update-fstab.yml
