---
- name: Add ,ro to /boot
  replace:
    path: /etc/fstab
    regexp: 'defaults,flush'
    replace: 'defaults,flush,ro'
    backup: yes

- name: Add ,ro to /
  replace:
    path: /etc/fstab
    regexp: 'defaults,noatime'
    replace: 'defaults,noatime,ro'
    backup: yes

- name: Add tmpfs to /etc/fstab
  blockinfile:
    path: /etc/fstab
    block: |
      tmpfs           /tmp            tmpfs   nosuid,nodev         0       0
      tmpfs           /var/log        tmpfs   nosuid,nodev         0       0
      tmpfs           /var/tmp        tmpfs   nosuid,nodev         0       0
